# Generated by Django 5.1 on 2024-09-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_category_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='categories',
            new_name='flags',
        ),
    ]
